// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package backend_masterclass

import (
	"database/sql"
	"time"
)

type Accounts struct {
	ID        int64
	Owner     string
	Balance   int64
	Currency  string
	CreatedAt time.Time
}

type Entries struct {
	ID        int64
	AccountID sql.NullInt64
	// can be negative or positive
	Amount    int64
	CreatedAt time.Time
}

type Transfers struct {
	ID          int64
	FromAccount sql.NullInt64
	ToAccount   sql.NullInt64
	// can only be positive
	Amout     int64
	CreatedAt time.Time
}
