// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package backend_masterclass

import (
	"time"
)

type Accounts struct {
	ID        int64
	Owner     string
	Balance   int64
	Currency  string
	CreatedAt time.Time
}

type Entries struct {
	ID        int64
	AccountID int64
	// can be negative or positive
	Amount    int64
	CreatedAt time.Time
}

type Transfers struct {
	ID          int64
	FromAccount int64
	ToAccount   int64
	// can only be positive
	Amout     int64
	CreatedAt time.Time
}
